language: node_js
node_js:
    - "node"
sudo: required
addons:
  chrome: stable
 script:
    - yarn test
    - yarn run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    local-dir: dist
    on:
      branch: master
